# Generated by Django 5.1.7 on 2025-05-15 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RegAndAuth', '0004_family_profile_family_familymember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('timezone', models.CharField(blank=True, max_length=20)),
                ('repeat_type', models.CharField(blank=True, max_length=20)),
                ('repeat_days', models.CharField(blank=True, max_length=50)),
                ('participants', models.TextField(blank=True)),
                ('priority', models.CharField(blank=True, default='normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_family_tasks', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='RegAndAuth.family')),
            ],
        ),
    ]
