# Generated by Django 5.1.7 on 2025-05-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyCalendar', '0002_familytask_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='familytask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
