# Generated by Django 5.1.7 on 2025-06-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePageUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='family_task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
