# Generated by Django 5.1.7 on 2025-05-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePageUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltask',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='personaltask',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personaltask',
            name='participants',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personaltask',
            name='repeat_days',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='personaltask',
            name='repeat_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='personaltask',
            name='timezone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
