# Generated by Django 5.1.7 on 2025-06-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePageUser', '0002_notification_family_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('personal', 'Личное'), ('family', 'Семейное')], default='personal', max_length=10),
        ),
    ]
