# Generated by Django 5.1.7 on 2025-05-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePageUser', '0002_personaltask_category_personaltask_is_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltask',
            name='priority',
            field=models.CharField(blank=True, default='normal', max_length=10),
        ),
    ]
