# Generated by Django 5.1.7 on 2025-05-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePageUser', '0003_personaltask_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
