# Generated by Django 5.1.7 on 2025-06-18 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyCalendar', '0001_initial'),
        ('HomePageUser', '0003_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='family_task_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='family_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='FamilyCalendar.familytask'),
        ),
    ]
