# Generated by Django 5.2 on 2025-04-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegAndAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='parent', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('parent', 'Родитель'), ('child', 'Ребенок')], default='parent', max_length=10),
        ),
    ]
